### ISSUE TITLE
 Feature Roadmap: Upcoming Features and Echancements

### ISSUE THREAD

**Issue by vlf-stefan-drobic** [openagri-eu/pest-and-disease-management#2]
This issue tracks all features and future releases. As features are implemented, they will be checked off and linked to their specific issues or pull requests.

#### Planned Features:

- [ ] **Specify interoperable ontology and integrate with OpenAgri Common Semantic Model**
  - Refactor input and output schemas to support OCSM models serialized in JSON-LD

- [ ] **Implement a versioning system**
  - Implement a versioning system alongside commits, that feature major and minor releases

- [ ] **Third-Party Integrations**
  - Integrate with GateKeeper as an API gateway service

Feel free to suggest additional features or comment on the proposed ones!

**Comment by vlf-stefan-drobic** [comment]
Last bit of work on this task resolved with: https://github.com/openagri-eu/OpenAgri-PestAndDiseaseManagement/pull/19

Closing as new issues will take it's place
